apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restreamer.fullname" . }}
  labels:
  {{- include "restreamer.labels" . | nindent 4 }}
stringData:
{{- range $k, $v := .Values.secretEnv }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
