apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "restreamer.fullname" . }}
  labels:
    {{- include "restreamer.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "restreamer.fullname" . }}
  selector:
    matchLabels:
      {{- include "restreamer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "restreamer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "restreamer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "restreamer.fullname" . }}
            - secretRef:
                name: {{ include "restreamer.fullname" . }}
          volumeMounts:
            - mountPath: /restreamer/db
              name: db
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              {{- if .Values.rtmp.hostPort.enabled }}
              hostPort: {{ .Values.rtmp.hostPort.port }}
              {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: db
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
{{- else if not .Values.persistence.enabled }}
        - name: db
          emptyDir: {}
{{- end }}
  volumeClaimTemplates:
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
    - metadata:
        name: db
        labels:
          app: "{{ template "restreamer.name" . }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{ include "restreamer.storageClass" . }}
{{- end }}
