apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "br0bot.fullname" . }}
  labels:
    app: {{ template "br0bot.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |-
    server:
      listenAddr: ":3000"
    database:
      driver: "{{ .Values.db.driver }}"
      postgres:
        host: "{{ .Values.db.postgresqlHost }}"
        port: "{{ .Values.db.postgresqlPort }}"
        dbName: "{{ .Values.db.postgresqlDatabase }}"
        user: "{{ .Values.db.postgresqlUsername }}"
        password: "{{ .Values.db.postgresqlPassword }}"
        ssl: "disable"
        timezone: "UTC"
    autoMigrate: false
    telegram:
      apiKey: "{{ .Values.bot.telegram.apiKey }}"
      baseUrl: "https://api.telegram.org/bot%s/"
      webhookUrl: "{{ .Values.bot.telegram.webhookurl }}"
      endpointSetWebhook: "setWebhook"
      endpointSendMessage: "sendMessage"
      endpointSendPhoto: "sendPhoto"
    stonksMatcher:
      quotesUrl: "https://query1.finance.yahoo.com/v7/finance/quote?symbols=%s"

  buzzwords.yaml: |-
    # Buzzword Configuration
    {{- if .Values.bot.buzzwords }}
    {{- toYaml .Values.bot.buzzwords | nindent 4 }}
    {{- end }}
