apiVersion: v2
name: br0bot
description: A Helm chart for Kubernetes
type: application
version: 0.2.3
appVersion: "0.1.1"
dependencies:
  - name: postgresql
    version: 10.4.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install
