apiVersion: v2
name: br0bot
description: A Helm chart for Kubernetes
type: application
version: 0.2.6
appVersion: "0.1.3"
dependencies:
  - name: postgresql
    version: 10.7.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install
